CREATE DATABASE inosio_test;

CREATE TABLE order(
    id INT(15) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    order VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DESCRIBE order;